package main

// DO NOT EDIT, this file is generated by hover at compile-time for the hwebview plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	hwebview "github.com/Winwisly100/hwebview/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&hwebview.HwebviewPlugin{}))
}
